### ISSUE TITLE
No module named _dionysus

### ISSUE THREAD

**Issue by tmelorc** [mrzv/dionysus#10]
Hello, I have just installed following procedures from here: [http://mrzv.org/software/dionysus2/](url). 

But I am not able to load it. See below what happens. Any help, please.

thiago@chumbinho ~ $ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import dionysus
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/thiago/dionysus/build/bindings/python/dionysus/__init__.py", line 2, in <module>
    from ._dionysus import *
ImportError: No module named _dionysus

**Comment by mrzv** [comment]
I'd need more information to debug this. What commands did you enter to install dionysus, and what was their output?

**Comment by tmelorc** [comment]
I did:

git clone https://github.com/mrzv/dionysus.git
mkdir build
cd build
cmake ..
make
export PYTHONPATH=.../build/bindings/python:$PYTHONPATH

I believe that everything was smooth. Then I opened another terminal and typed as in previous message.

Let me inform that yesterday I also tried to install Dionysus 1 via pip and some examples was working but not the one using alpha2d.

If necessary, no problem to remove and start from beginning. 
Thanks.

**Comment by mrzv** [comment]
You have to run `export PYTHONPATH=...` from the same terminal from which you are going to launch python. It's not a global command. (To make it global, you need to add it to your `.bashrc` or `.zshrc`, or something else, depending on the terminal you are using.)

I also don't understand the remark about Dionysus 1; there are no `pip` packages for Dionysus 1 that I know of.
