### ISSUE TITLE
Alive cycles in zig-zag persistent homology

### ISSUE THREAD

**Issue by padraigc9** [mrzv/dionysus#14]
In Dionysus 2 one cannot examine the alive cycles at each time step. Instead one can only examine alive cycles at the end.

**Comment by mrzv** [comment]
I've pushed changes that let you examine the cycles after every step of the zigzag. See the last example in [zigzags section](http://mrzv.org/software/dionysus2/tutorial/zigzags.html).

Let me know if this works for what you want, so I can close this issue.

**Comment by mrzv** [comment]
Actually, as I'm looking at the code, I realize that the cycles are output in terms of internal indices (which are the addition order, i.e., which simplex addition, in order, added the simplex that's the element in the cycle). This may not be the ideal output, although that's orthogonal to the original issue (this problem exists with `zigzag_persistent_homology` output in general).

**Comment by mrzv** [comment]
I've now pushed the changes to make it easy to get representative cycles from the internal representation. There are [examples in the documentation](http://mrzv.org/software/dionysus2/tutorial/zigzags.html#representative-cycles).

I'm going to close this issue. Feel free to reopen, if something is unresolved.
