### ISSUE TITLE
Building problem on Windows 10

### ISSUE THREAD

**Issue by weihnachtskugel** [mrzv/dionysus#15]
After newly installing boost, cmake and pip with conda I cannot get rid of
`...

    copying bindings\python\dionysus\__init__.py -> build\lib.win-amd64-3.6\dionysus

    running build_ext

    -- Building for: NMake Makefiles

    CMake Error at CMakeLists.txt:1 (project):

      Generator
        NMake Makefiles
      does not support platform specification, but platform
        x64
      was specified.
    CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
    CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
    -- Configuring incomplete, errors occurred! ... `
when using `pip install dionysus`. Any help is greatly appreciated.

**Comment by mrzv** [comment]
I'm afraid I have no experience with Windows. It looks like CMake is unable to find the C/C++ compiler, but why that is, I don't know. You could try emailing the mailing list, to see if anybody can help you there.

**Comment by lupangsogood** [comment]
https://stackoverflow.com/questions/54967887/solution-install-dlibpython-and-get-error

**Comment by prostospirit** [comment]
I had the same problem and resolved it.
Install Visual C++ and Python tools for Visual Studio
Delete your Anaconda, download new version from official site and install it according this instruction: https://www.learnopencv.com/install-opencv-3-and-dlib-on-windows-python-only/

**Comment by mrzv** [comment]
@prostospirit If you managed to compile Dionysus on Windows, do you mind writing up instructions on how to do it (the more detailed, the better)? For one, I'd love to know myself — I never succeeded on Windows — and it's a frequent enough question that I'd like to include it in the documentation.

**Comment by prostospirit** [comment]
@mrzv Я никогда не использовал 
dionysus. Эту проблему необходимо решать индивудуально. Но обычно, если встречается эта ошибка, то необходимо проверить все пакеты содержащие C++. Насколько мне сейчас известно, перед использованием С++ библиотек необходимо установить Visual Studio 2015 or newer с установкой всех пакетов, необходимых для работы с C++.
![image](https://user-images.githubusercontent.com/48649902/56684491-8b723e80-66d8-11e9-8cce-0a5f3b1e20bf.png)

После этого, если ошибка не исчезла установить cmake https://cmake.org/download/. Если ошибка всё ещё есть, попробовать установить в виртуальную среду один из пакетов: 
https://pypi.org/project/cmake/
https://anaconda.org/conda-forge/cmake
https://anaconda.org/anaconda/cmake
Я имею малый опыт работы с CMake в Python, но большинство проблем такого характера решались таким способом
