### ISSUE TITLE
Failing to build-Cygwin

### ISSUE THREAD

**Issue by enoelbrown** [mrzv/dionysus#17]
Hello! I'm new to much of this, but I've tried many ways to get Dionysus 2 installed on my Windows 10 PC in Python2, Python3, Visual Studio 2017, and now Cygwin. Focusing just on Cygwin, CMake appears to successfully create the build files. But when I run Make, in the build directory, what I get is below. Cygwin has gcc 6.4.0 installed, along with Boost 1.66. Any insight at all would be helpful, even though I've read from your previous posts that you're not a Windows user. Thanks.

$ make
Scanning dependencies of target zigzag-filtration-persistence
[  2%] Building CXX object examples/filtration/CMakeFiles/zigzag-filtration-persistence.dir/zigzag-filtration-persistence.cpp.o
In file included from /home/dionysus-master/examples/include/format/format.h:2543:0,
                 from /home/dionysus-master/examples/include/format.h:6,
                 from /home/dionysus-master/examples/filtration/zigzag-filtration-persistence.cpp:15:
/home/dionysus-master/examples/include/format/format.cc: In function ‘int {anonymous}::safe_strerror(int, char*&, std::size_t)’:
/home/dionysus-master/examples/include/format/format.cc:162:54: error: ‘strerror_r’ was not declared in this scope
   result = strerror_r(error_code, buffer, buffer_size);
                                                      ^
make[2]: *** [examples/filtration/CMakeFiles/zigzag-filtration-persistence.dir/build.make:63: examples/filtration/CMakeFiles/zigzag-filtration-persistence.dir/zigzag-filtration-persistence.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:115: examples/filtration/CMakeFiles/zigzag-filtration-persistence.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by mrzv** [comment]
Can you write to the mailing list with this problem? Just last week, somebody figured out how to compile Dionysus under Windows using MinGW. In fact, even how to install it using pip, using MinGW.

I don't use Windows, so it's difficult for me to address the problems on the issue tracker. So I'm going to close this issue.
