### ISSUE TITLE
Print progress

### ISSUE THREAD

**Issue by sauln** [mrzv/dionysus#19]
Is it possible to track how long the computations will take and intermittently print information about progress?

For example, Keras will print progress information during the fitting process.

```
Epoch 1/100
0s - loss: 0.2506 - acc: 0.5750 - val_loss: 0.2501 - val_acc: 0.3750
Epoch 2/100
0s - loss: 0.2487 - acc: 0.6250 - val_loss: 0.2498 - val_acc: 0.6250
Epoch 3/100
0s - loss: 0.2495 - acc: 0.5750 - val_loss: 0.2496 - val_acc: 0.6250
```

This would be very helpful, as it is currently not clear how long computations will take.

**Comment by mrzv** [comment]
Which functions do you want to have this kind of output?

**Comment by sauln** [comment]
I believe `homology_persistence` is the most time intensive function that I am currently using.

**Comment by mrzv** [comment]
There is a solution now on `master`. Pass `progress = True` to `homology_persistence(...)`, and it will show a progress bar.

Let me know if it works for you.

**Comment by sauln** [comment]
Thanks for addressing this so quickly! 

When running Dionysus in Jupyter notebooks, the output is to the terminal rather than in the Jupyter notebook itself. 

<img width="569" alt="screen shot 2018-05-02 at 10 18 20 am" src="https://user-images.githubusercontent.com/5808961/39538614-34509002-4df2-11e8-8d9d-a45c16a3452b.png">

Is it possible to redirect the output to the more natural location? This might be more work than it's worth. [This blog](https://eli.thegreenplace.net/2015/redirecting-all-kinds-of-stdout-in-python/) seems to be the more comprehensive coverage of the process.

**Comment by mrzv** [comment]
Try it now.

**Comment by sauln** [comment]
That works great! Thank you!

<img width="740" alt="screen shot 2018-05-02 at 12 37 03 pm" src="https://user-images.githubusercontent.com/5808961/39545289-914527ba-4e05-11e8-8d2b-86a05f699f26.png">
