### ISSUE TITLE
Bottleneck Distances

### ISSUE THREAD

**Issue by aspannaus79** [mrzv/dionysus#22]
I am having an issue when computing the bottleneck distance between two diagrams. When both persistence diagrams have a point that has inf as its death time, the bottleneck distance seems to hang and not return a value. 

As a simple example, consider:
import dionysus as d
dgm1 = d.Diagram([(1,2), (3,4), (1., float('inf'))])
dgm2 = d.Diagram([(0,2), (3,5), (2., float('inf'))])
d.bottleneck_distance(dgm1,dgm2)

**Comment by mrzv** [comment]
Try it now.
