### ISSUE TITLE
Zigzag persistence calculation hangs in Python 3.7

### ISSUE THREAD

**Issue by nhchristianson** [mrzv/dionysus#28]
When I try to calculate zigzag persistence, as in the example in the documentation, Python 3.7 hangs:

`Python 3.7.0 (default, Jul  9 2018, 16:42:22) 
[Clang 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dionysus as d
>>> f = d.Filtration([[0], [1], [0,1], [2], [0,2], [1,2]])
>>> times = [[.4, .6, .7], [.1], [.9], [.9], [.9], [.9]]
>>> zz, dgms, cells = d.zigzag_homology_persistence(f, times)`
(nothing happens, Python no longer responds)

I've tried installing the PyPI version as well as the current development version on the repository via pip; I've also cloned and built the repository on my own. This does not occur in Python 3.6.

**Comment by mrzv** [comment]
Just a quick confirmation that I see the problem. I haven't yet figured out what's causing it.

**Comment by mrzv** [comment]
This should now be fixed on `master`. Give it a try. I'm going to close this issue, but feel free to reopen it, if it doesn't work for you.
