### ISSUE TITLE
How to know which points form some bar code

### ISSUE THREAD

**Issue by HongyuanZhang** [mrzv/dionysus#29]
Hi,

For a bar code, is it possible to know which points form this bar code? For example, if I use a distance matrix to create a filtration and then a reduced matrix, then I generate the bar code graph for the first dimension. If I have a bar code that lasts for an interval [a, b) in the first dimension, could I know which data points form this loop (a 1-dimensional bar code represents a loop)?

Thanks,

Hongyuan

**Comment by mrzv** [comment]
This is not an issue with the code. Please send such questions to the mailing list.
