### ISSUE TITLE
Installation failed on Windows 10

### ISSUE THREAD

**Issue by nihell** [mrzv/dionysus#41]
Hi,
I'm using Anaconda with Python 3.7 on Windows 10.
`conda install -c conda-forge dionysus` doesn't work and `conda search dionysus --channel conda-forge` doesn't find anything, so I tried `pip install dionysus`, which found the package, but failed to install it. Please find the log attached.

Cheers,
Niklas
[dionysus_log.txt](https://github.com/mrzv/dionysus/files/4528634/dionysus_log.txt)

**Comment by mrzv** [comment]
I don't use Windows, so it's not something I can resolve. The issue of building on Windows has come up before (#9, #15, #17), with [some helpful information on the mailing list](https://groups.io/g/dionysus/topic/build_under_windows/32045298?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,32045298).
