### ISSUE TITLE
Incorrect Homologies with Lower-star filtration

### ISSUE THREAD

**Issue by JanRocketMan** [mrzv/dionysus#44]
Hi!

It looks like there is a bug in the pybind code that implements "fill_freudenthal" method. Here's an example:

```python
import dionysus as d
import numpy as np
import matplotlib.pyplot as plt

ex_arr = np.array([
       [5 , 4, 0],
       [3, 6, 7],
       [1, 8, 2]
]).astype('float')

plt.matshow(ex_arr)
plt.show()

f_lower_star = d.fill_freudenthal(ex_arr)

homology_persistence = d.homology_persistence(f_lower_star)
dgms = d.init_diagrams(homology_persistence, f_lower_star)

d.plot.plot_diagram(dgms[0])
plt.show()

print("Answer:", [d for d in dgms[0]])
```

Returns persistence features [(0,inf), (1,5), (2,6)], while the correct answer is [(0,inf), (1,4), (2,6)] (this is given by ripser as well). 

It seems that for some reason f_lower_star doesn't contain the edge <1,3> in it's filtration sequence, which should appear at step 4, hence reduction gives wrong answer...

**Comment by mrzv** [comment]
But `<1,3>` doesn't belong to the Freudenthal triangulation. It's correct not to add it. Perhaps the indexing is confusing? The coordinate system on the rows goes down, not up, to match the usual matrix notation.

**Comment by JanRocketMan** [comment]
Oh, I get it. Is there a way I can switch it to a more straightforward simplex where I connect each point to 8 of its neighbors?

**Comment by mrzv** [comment]
You'd need to implement that yourself, but that's probably 5 lines in Python.

**Comment by JanRocketMan** [comment]
Do I have to write pybind code for this, to get the filtration of type _dionysus.Filtration that I can pass in homology_persistence?

**Comment by JanRocketMan** [comment]
Sorry, I can't understand how to create one - the page with API doesn't provide any __init__ methods for the Simplex or FIltration classes, and I simply couldn't find what arguments should I pass there. Could you please explain on why do I need an index class and what methods is required for it?

**Comment by mrzv** [comment]
Simplex vertices must be integers. `index(...)` here is a function to map two coordinates, `x,y`, to a linear index `u`. `Simplex` takes a list of vertices and a floating point value that's associated to it. (For what you want the value should be the maximum of the two vertex values.)

**Comment by JanRocketMan** [comment]
Thanks, it works fine this way.
