### ISSUE TITLE
cmake does not create makefile

### ISSUE THREAD

**Issue by eahogan** [mrzv/dionysus#52]
I am running on Windows 10 and finally made it through the cmake process (after installing CMake, Visual C++, and Boost). It seems like it completes properly. But when I then run make I get:
`make: *** No targets specified and no makefile found.  Stop.`

My output from running `cmake ..` from the `build` subdirectory is here:
[cmake_output.txt](https://github.com/mrzv/dionysus/files/7982852/cmake_output.txt)

The contents of the build directory populate through the cmake as:
> /build
/CMakeFiles
/examples
ALL_BUILD.vcxproj
ALL_BUILD.vcsproj.filters
cmake_install.cmake
CMakeCache.txt
Dionysus.sh
ZERO_CHECK.vcxproj
ZERO_CHECK.vcxproj.filters

There is no Makefile created.

**Comment by mrzv** [comment]
Can you try running `cmake --build .`?

**Comment by eahogan** [comment]
Tried that and got a whole pile of new errors. Rather than dumping that all here I'm going to try the tips here https://groups.io/g/dionysus/topic/23024190#59 next. I was just pointed to that thread by a colleague.

**Comment by mrzv** [comment]
Yup, that was going to be my next suggestion.  I was hoping that you'd somehow gotten farther along than the previous attempts. I'm going to close this issue. Feel free to reopen, if needed.
