### ISSUE TITLE
issue with installing on windows

### ISSUE THREAD

**Issue by panzerrunne** [mrzv/dionysus#55]
I getting an error when I am trying to install dionysus on my windows machine (I know linux is better).  The issue seems to be related to setuptools. Is there any workaround for this. I have python 3.10.7 and pip  22.2.2 and setuptools seems to be installed. 
thank you  

  × Running setup.py install for dionysus did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: 'C:\Users\pkudela1\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe' -u -c '
  exec(compile('"'"''"'"''"'"'
  # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
  #
  # - It imports setuptools before invoking setup.py, to enable projects that directly
  #   import from `distutils.core` to work with newer packaging standards.
  # - It provides a clear error message when setuptools is not installed.
  # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
  #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
  #     manifest_maker: standard file '"'"'-c'"'"' not found".
  # - It generates a shim setup.py, for handling setup.cfg-only projects.
  import os, sys, tokenize

  try:
      import setuptools
  except ImportError as error:
      print(
          "ERROR: Can not execute `setup.py` since setuptools is not available in "
          "the build environment.",
          file=sys.stderr,
      )
      sys.exit(1)

  __file__ = %r
  sys.argv[0] = __file__

  if os.path.exists(__file__):
      filename = __file__
      with tokenize.open(__file__) as f:
          setup_py_code = f.read()
  else:
      filename = "<auto-generated setuptools caller>"
      setup_py_code = "from setuptools import setup; setup()"

  exec(compile(setup_py_code, filename, "exec"))
  '"'"''"'"''"'"' % ('"'"'C:\\Users\\pkudela1\\AppData\\Local\\Temp\\pip-req-build-twzf6oui\\setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' install --record 'C:\Users\pkudela1\AppData\Local\Temp\pip-record-mf61_egy\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\pkudela1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Include\dionysus'
  cwd: C:\Users\pkudela1\AppData\Local\Temp\pip-req-build-twzf6oui\
  Running setup.py install for dionysus ... error
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> dionysus

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by mrzv** [comment]
I know nothing about Windows, so as far as I'm concerned it's not supported. Some people on the mailing list have posted about it in the past, so that might be helpful. The easiest way to get this to run on Windows is inside the Linux subsystem that Windows provides.

I'm going to close this, since I cannot provide any useful advice.

**Comment by panzerrunne** [comment]
No worries and thanks for getting back to me.
