### ISSUE TITLE
Make fails: 

### ISSUE THREAD

**Issue by yossibokor** [mrzv/dionysus#58]
Following
```bash
mkdir build
cd build
cmake ..
make
```
I obtain the following error:
```bash
error: ‘numeric_limits’ is not a member of ‘std’
```

which i fixed locally by adding ```#Include <limits>``` to ```dionysus/include/dionysus/reduction.h``` and ```dionysus/include/dionysus/diagram.h```

Occurs on both Linux (Ubuntu 22.04) and MacOS (Ventura).

**Comment by mrzv** [comment]
Fixed. Thanks, Yossi.
